"""Add filed activated for Currency and update CryptoPulse.currency

Revision ID: 4643eb841c02
Revises: 97589606bd73
Create Date: 2024-09-24 16:16:28.367725

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "4643eb841c02"
down_revision: Union[str, None] = "97589606bd73"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "currency", sa.Column("activated", sa.Boolean(), nullable=False)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("currency", "activated")
    # ### end Alembic commands ###
