"""Update decimal fields

Revision ID: 76b64b8bcbee
Revises: 3943b6d26941
Create Date: 2024-09-29 11:22:33.739900

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "76b64b8bcbee"
down_revision: Union[str, None] = "3943b6d26941"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "cryptopulse",
        "max_price",
        existing_type=sa.NUMERIC(precision=20, scale=10),
        type_=sa.DECIMAL(precision=40, scale=5),
        existing_nullable=False,
    )
    op.alter_column(
        "cryptopulse",
        "open_interest",
        existing_type=sa.NUMERIC(precision=20, scale=10),
        type_=sa.DECIMAL(precision=40, scale=5),
        existing_nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "cryptopulse",
        "open_interest",
        existing_type=sa.DECIMAL(precision=40, scale=5),
        type_=sa.NUMERIC(precision=20, scale=10),
        existing_nullable=False,
    )
    op.alter_column(
        "cryptopulse",
        "max_price",
        existing_type=sa.DECIMAL(precision=40, scale=5),
        type_=sa.NUMERIC(precision=20, scale=10),
        existing_nullable=False,
    )
    # ### end Alembic commands ###
