"""Update time fields and move max_price and open_interest from Currency to CryptoPulse

Revision ID: 97589606bd73
Revises: f63f03749fdd
Create Date: 2024-09-18 22:41:23.759501

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "97589606bd73"
down_revision: Union[str, None] = "f63f03749fdd"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "cryptopulse", sa.Column("max_price", sa.Float(), nullable=False)
    )
    op.add_column(
        "cryptopulse", sa.Column("open_interest", sa.Float(), nullable=False)
    )
    op.drop_column("currency", "max_price")
    op.drop_column("currency", "open_interest")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "currency",
        sa.Column(
            "open_interest",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.add_column(
        "currency",
        sa.Column(
            "max_price",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.drop_column("cryptopulse", "open_interest")
    op.drop_column("cryptopulse", "max_price")
    # ### end Alembic commands ###
