"""Change float to decimal

Revision ID: 3943b6d26941
Revises: 4643eb841c02
Create Date: 2024-09-28 18:53:04.373327

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "3943b6d26941"
down_revision: Union[str, None] = "4643eb841c02"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "cryptopulse",
        "max_price",
        existing_type=sa.DOUBLE_PRECISION(precision=53),
        type_=sa.DECIMAL(precision=20, scale=10),
        existing_nullable=False,
    )
    op.alter_column(
        "cryptopulse",
        "open_interest",
        existing_type=sa.DOUBLE_PRECISION(precision=53),
        type_=sa.DECIMAL(precision=20, scale=10),
        existing_nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "cryptopulse",
        "open_interest",
        existing_type=sa.DECIMAL(precision=20, scale=10),
        type_=sa.DOUBLE_PRECISION(precision=53),
        existing_nullable=False,
    )
    op.alter_column(
        "cryptopulse",
        "max_price",
        existing_type=sa.DECIMAL(precision=20, scale=10),
        type_=sa.DOUBLE_PRECISION(precision=53),
        existing_nullable=False,
    )
    # ### end Alembic commands ###
